name             'ntp'
maintainer       'Jaime Gil de Sagredo'
maintainer_email 'jaimegildesagredo@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures ntp'
version          '0.1.0'
