name             'the_silver_searcher'
maintainer       'Jaime Gil de Sagredo'
maintainer_email 'jaimegildesagredo@gmail.com'
license          'All rights reserved'
description      'Installs/Configures the_silver_searcher'
version          '0.1.0'
